// Code generated by ent, DO NOT EDIT.

package adminconfig

import (
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldID, id))
}

// OtelEndpoint applies equality check predicate on the "otel_endpoint" field. It's identical to OtelEndpointEQ.
func OtelEndpoint(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// TracesEnabled applies equality check predicate on the "traces_enabled" field. It's identical to TracesEnabledEQ.
func TracesEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTracesEnabled, v))
}

// MetricsEnabled applies equality check predicate on the "metrics_enabled" field. It's identical to MetricsEnabledEQ.
func MetricsEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldMetricsEnabled, v))
}

// LogsEnabled applies equality check predicate on the "logs_enabled" field. It's identical to LogsEnabledEQ.
func LogsEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogsEnabled, v))
}

// LogSeverity applies equality check predicate on the "log_severity" field. It's identical to LogSeverityEQ.
func LogSeverity(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogSeverity, v))
}

// GotifyURL applies equality check predicate on the "gotify_url" field. It's identical to GotifyURLEQ.
func GotifyURL(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyToken applies equality check predicate on the "gotify_token" field. It's identical to GotifyTokenEQ.
func GotifyToken(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldGotifyToken, v))
}

// TelegramBotToken applies equality check predicate on the "telegram_bot_token" field. It's identical to TelegramBotTokenEQ.
func TelegramBotToken(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTelegramBotToken, v))
}

// TelegramChatID applies equality check predicate on the "telegram_chat_id" field. It's identical to TelegramChatIDEQ.
func TelegramChatID(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTelegramChatID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// OtelEndpointEQ applies the EQ predicate on the "otel_endpoint" field.
func OtelEndpointEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// OtelEndpointNEQ applies the NEQ predicate on the "otel_endpoint" field.
func OtelEndpointNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldOtelEndpoint, v))
}

// OtelEndpointIn applies the In predicate on the "otel_endpoint" field.
func OtelEndpointIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointNotIn applies the NotIn predicate on the "otel_endpoint" field.
func OtelEndpointNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointGT applies the GT predicate on the "otel_endpoint" field.
func OtelEndpointGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldOtelEndpoint, v))
}

// OtelEndpointGTE applies the GTE predicate on the "otel_endpoint" field.
func OtelEndpointGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldOtelEndpoint, v))
}

// OtelEndpointLT applies the LT predicate on the "otel_endpoint" field.
func OtelEndpointLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldOtelEndpoint, v))
}

// OtelEndpointLTE applies the LTE predicate on the "otel_endpoint" field.
func OtelEndpointLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldOtelEndpoint, v))
}

// OtelEndpointContains applies the Contains predicate on the "otel_endpoint" field.
func OtelEndpointContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldOtelEndpoint, v))
}

// OtelEndpointHasPrefix applies the HasPrefix predicate on the "otel_endpoint" field.
func OtelEndpointHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldOtelEndpoint, v))
}

// OtelEndpointHasSuffix applies the HasSuffix predicate on the "otel_endpoint" field.
func OtelEndpointHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldOtelEndpoint, v))
}

// OtelEndpointIsNil applies the IsNil predicate on the "otel_endpoint" field.
func OtelEndpointIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldOtelEndpoint))
}

// OtelEndpointNotNil applies the NotNil predicate on the "otel_endpoint" field.
func OtelEndpointNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldOtelEndpoint))
}

// OtelEndpointEqualFold applies the EqualFold predicate on the "otel_endpoint" field.
func OtelEndpointEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldOtelEndpoint, v))
}

// OtelEndpointContainsFold applies the ContainsFold predicate on the "otel_endpoint" field.
func OtelEndpointContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldOtelEndpoint, v))
}

// TracesEnabledEQ applies the EQ predicate on the "traces_enabled" field.
func TracesEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTracesEnabled, v))
}

// TracesEnabledNEQ applies the NEQ predicate on the "traces_enabled" field.
func TracesEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldTracesEnabled, v))
}

// MetricsEnabledEQ applies the EQ predicate on the "metrics_enabled" field.
func MetricsEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldMetricsEnabled, v))
}

// MetricsEnabledNEQ applies the NEQ predicate on the "metrics_enabled" field.
func MetricsEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldMetricsEnabled, v))
}

// LogsEnabledEQ applies the EQ predicate on the "logs_enabled" field.
func LogsEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogsEnabled, v))
}

// LogsEnabledNEQ applies the NEQ predicate on the "logs_enabled" field.
func LogsEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldLogsEnabled, v))
}

// LogSeverityEQ applies the EQ predicate on the "log_severity" field.
func LogSeverityEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogSeverity, v))
}

// LogSeverityNEQ applies the NEQ predicate on the "log_severity" field.
func LogSeverityNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldLogSeverity, v))
}

// LogSeverityIn applies the In predicate on the "log_severity" field.
func LogSeverityIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldLogSeverity, vs...))
}

// LogSeverityNotIn applies the NotIn predicate on the "log_severity" field.
func LogSeverityNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldLogSeverity, vs...))
}

// LogSeverityGT applies the GT predicate on the "log_severity" field.
func LogSeverityGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldLogSeverity, v))
}

// LogSeverityGTE applies the GTE predicate on the "log_severity" field.
func LogSeverityGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldLogSeverity, v))
}

// LogSeverityLT applies the LT predicate on the "log_severity" field.
func LogSeverityLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldLogSeverity, v))
}

// LogSeverityLTE applies the LTE predicate on the "log_severity" field.
func LogSeverityLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldLogSeverity, v))
}

// LogSeverityContains applies the Contains predicate on the "log_severity" field.
func LogSeverityContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldLogSeverity, v))
}

// LogSeverityHasPrefix applies the HasPrefix predicate on the "log_severity" field.
func LogSeverityHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldLogSeverity, v))
}

// LogSeverityHasSuffix applies the HasSuffix predicate on the "log_severity" field.
func LogSeverityHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldLogSeverity, v))
}

// LogSeverityEqualFold applies the EqualFold predicate on the "log_severity" field.
func LogSeverityEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldLogSeverity, v))
}

// LogSeverityContainsFold applies the ContainsFold predicate on the "log_severity" field.
func LogSeverityContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldLogSeverity, v))
}

// GotifyURLEQ applies the EQ predicate on the "gotify_url" field.
func GotifyURLEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldGotifyURL, v))
}

// GotifyURLNEQ applies the NEQ predicate on the "gotify_url" field.
func GotifyURLNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldGotifyURL, v))
}

// GotifyURLIn applies the In predicate on the "gotify_url" field.
func GotifyURLIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldGotifyURL, vs...))
}

// GotifyURLNotIn applies the NotIn predicate on the "gotify_url" field.
func GotifyURLNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldGotifyURL, vs...))
}

// GotifyURLGT applies the GT predicate on the "gotify_url" field.
func GotifyURLGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldGotifyURL, v))
}

// GotifyURLGTE applies the GTE predicate on the "gotify_url" field.
func GotifyURLGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldGotifyURL, v))
}

// GotifyURLLT applies the LT predicate on the "gotify_url" field.
func GotifyURLLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldGotifyURL, v))
}

// GotifyURLLTE applies the LTE predicate on the "gotify_url" field.
func GotifyURLLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldGotifyURL, v))
}

// GotifyURLContains applies the Contains predicate on the "gotify_url" field.
func GotifyURLContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldGotifyURL, v))
}

// GotifyURLHasPrefix applies the HasPrefix predicate on the "gotify_url" field.
func GotifyURLHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldGotifyURL, v))
}

// GotifyURLHasSuffix applies the HasSuffix predicate on the "gotify_url" field.
func GotifyURLHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldGotifyURL, v))
}

// GotifyURLIsNil applies the IsNil predicate on the "gotify_url" field.
func GotifyURLIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldGotifyURL))
}

// GotifyURLNotNil applies the NotNil predicate on the "gotify_url" field.
func GotifyURLNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldGotifyURL))
}

// GotifyURLEqualFold applies the EqualFold predicate on the "gotify_url" field.
func GotifyURLEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldGotifyURL, v))
}

// GotifyURLContainsFold applies the ContainsFold predicate on the "gotify_url" field.
func GotifyURLContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldGotifyURL, v))
}

// GotifyTokenEQ applies the EQ predicate on the "gotify_token" field.
func GotifyTokenEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldGotifyToken, v))
}

// GotifyTokenNEQ applies the NEQ predicate on the "gotify_token" field.
func GotifyTokenNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldGotifyToken, v))
}

// GotifyTokenIn applies the In predicate on the "gotify_token" field.
func GotifyTokenIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldGotifyToken, vs...))
}

// GotifyTokenNotIn applies the NotIn predicate on the "gotify_token" field.
func GotifyTokenNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldGotifyToken, vs...))
}

// GotifyTokenGT applies the GT predicate on the "gotify_token" field.
func GotifyTokenGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldGotifyToken, v))
}

// GotifyTokenGTE applies the GTE predicate on the "gotify_token" field.
func GotifyTokenGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldGotifyToken, v))
}

// GotifyTokenLT applies the LT predicate on the "gotify_token" field.
func GotifyTokenLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldGotifyToken, v))
}

// GotifyTokenLTE applies the LTE predicate on the "gotify_token" field.
func GotifyTokenLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldGotifyToken, v))
}

// GotifyTokenContains applies the Contains predicate on the "gotify_token" field.
func GotifyTokenContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldGotifyToken, v))
}

// GotifyTokenHasPrefix applies the HasPrefix predicate on the "gotify_token" field.
func GotifyTokenHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldGotifyToken, v))
}

// GotifyTokenHasSuffix applies the HasSuffix predicate on the "gotify_token" field.
func GotifyTokenHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldGotifyToken, v))
}

// GotifyTokenIsNil applies the IsNil predicate on the "gotify_token" field.
func GotifyTokenIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldGotifyToken))
}

// GotifyTokenNotNil applies the NotNil predicate on the "gotify_token" field.
func GotifyTokenNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldGotifyToken))
}

// GotifyTokenEqualFold applies the EqualFold predicate on the "gotify_token" field.
func GotifyTokenEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldGotifyToken, v))
}

// GotifyTokenContainsFold applies the ContainsFold predicate on the "gotify_token" field.
func GotifyTokenContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldGotifyToken, v))
}

// TelegramBotTokenEQ applies the EQ predicate on the "telegram_bot_token" field.
func TelegramBotTokenEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTelegramBotToken, v))
}

// TelegramBotTokenNEQ applies the NEQ predicate on the "telegram_bot_token" field.
func TelegramBotTokenNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldTelegramBotToken, v))
}

// TelegramBotTokenIn applies the In predicate on the "telegram_bot_token" field.
func TelegramBotTokenIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldTelegramBotToken, vs...))
}

// TelegramBotTokenNotIn applies the NotIn predicate on the "telegram_bot_token" field.
func TelegramBotTokenNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldTelegramBotToken, vs...))
}

// TelegramBotTokenGT applies the GT predicate on the "telegram_bot_token" field.
func TelegramBotTokenGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldTelegramBotToken, v))
}

// TelegramBotTokenGTE applies the GTE predicate on the "telegram_bot_token" field.
func TelegramBotTokenGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldTelegramBotToken, v))
}

// TelegramBotTokenLT applies the LT predicate on the "telegram_bot_token" field.
func TelegramBotTokenLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldTelegramBotToken, v))
}

// TelegramBotTokenLTE applies the LTE predicate on the "telegram_bot_token" field.
func TelegramBotTokenLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldTelegramBotToken, v))
}

// TelegramBotTokenContains applies the Contains predicate on the "telegram_bot_token" field.
func TelegramBotTokenContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldTelegramBotToken, v))
}

// TelegramBotTokenHasPrefix applies the HasPrefix predicate on the "telegram_bot_token" field.
func TelegramBotTokenHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldTelegramBotToken, v))
}

// TelegramBotTokenHasSuffix applies the HasSuffix predicate on the "telegram_bot_token" field.
func TelegramBotTokenHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldTelegramBotToken, v))
}

// TelegramBotTokenIsNil applies the IsNil predicate on the "telegram_bot_token" field.
func TelegramBotTokenIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldTelegramBotToken))
}

// TelegramBotTokenNotNil applies the NotNil predicate on the "telegram_bot_token" field.
func TelegramBotTokenNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldTelegramBotToken))
}

// TelegramBotTokenEqualFold applies the EqualFold predicate on the "telegram_bot_token" field.
func TelegramBotTokenEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldTelegramBotToken, v))
}

// TelegramBotTokenContainsFold applies the ContainsFold predicate on the "telegram_bot_token" field.
func TelegramBotTokenContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldTelegramBotToken, v))
}

// TelegramChatIDEQ applies the EQ predicate on the "telegram_chat_id" field.
func TelegramChatIDEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTelegramChatID, v))
}

// TelegramChatIDNEQ applies the NEQ predicate on the "telegram_chat_id" field.
func TelegramChatIDNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldTelegramChatID, v))
}

// TelegramChatIDIn applies the In predicate on the "telegram_chat_id" field.
func TelegramChatIDIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDNotIn applies the NotIn predicate on the "telegram_chat_id" field.
func TelegramChatIDNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDGT applies the GT predicate on the "telegram_chat_id" field.
func TelegramChatIDGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldTelegramChatID, v))
}

// TelegramChatIDGTE applies the GTE predicate on the "telegram_chat_id" field.
func TelegramChatIDGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldTelegramChatID, v))
}

// TelegramChatIDLT applies the LT predicate on the "telegram_chat_id" field.
func TelegramChatIDLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldTelegramChatID, v))
}

// TelegramChatIDLTE applies the LTE predicate on the "telegram_chat_id" field.
func TelegramChatIDLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldTelegramChatID, v))
}

// TelegramChatIDContains applies the Contains predicate on the "telegram_chat_id" field.
func TelegramChatIDContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldTelegramChatID, v))
}

// TelegramChatIDHasPrefix applies the HasPrefix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldTelegramChatID, v))
}

// TelegramChatIDHasSuffix applies the HasSuffix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldTelegramChatID, v))
}

// TelegramChatIDIsNil applies the IsNil predicate on the "telegram_chat_id" field.
func TelegramChatIDIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldTelegramChatID))
}

// TelegramChatIDNotNil applies the NotNil predicate on the "telegram_chat_id" field.
func TelegramChatIDNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldTelegramChatID))
}

// TelegramChatIDEqualFold applies the EqualFold predicate on the "telegram_chat_id" field.
func TelegramChatIDEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldTelegramChatID, v))
}

// TelegramChatIDContainsFold applies the ContainsFold predicate on the "telegram_chat_id" field.
func TelegramChatIDContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldTelegramChatID, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.NotPredicates(p))
}
