// Code generated by ent, DO NOT EDIT.

package servicelink

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the servicelink type in the database.
	Label = "service_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContainer holds the string denoting the container field in the database.
	FieldContainer = "container"
	// FieldService holds the string denoting the service field in the database.
	FieldService = "service"
	// FieldReference holds the string denoting the reference field in the database.
	FieldReference = "reference"
	// FieldLiveState holds the string denoting the live_state field in the database.
	FieldLiveState = "live_state"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the servicelink in the database.
	Table = "service_links"
)

// Columns holds all SQL columns for servicelink fields.
var Columns = []string{
	FieldID,
	FieldContainer,
	FieldService,
	FieldReference,
	FieldLiveState,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLiveState holds the default value on creation for the "live_state" field.
	DefaultLiveState string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Service defines the type for the "service" enum field.
type Service string

// Service values.
const (
	ServiceUptimeKuma Service = "uptime_kuma"
	ServiceNpm        Service = "npm"
	ServiceAuthelia   Service = "authelia"
)

func (s Service) String() string {
	return string(s)
}

// ServiceValidator is a validator for the "service" field enum values. It is called by the builders before save.
func ServiceValidator(s Service) error {
	switch s {
	case ServiceUptimeKuma, ServiceNpm, ServiceAuthelia:
		return nil
	default:
		return fmt.Errorf("servicelink: invalid enum value for service field: %q", s)
	}
}

// OrderOption defines the ordering options for the ServiceLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByContainer orders the results by the container field.
func ByContainer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainer, opts...).ToFunc()
}

// ByService orders the results by the service field.
func ByService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldService, opts...).ToFunc()
}

// ByReference orders the results by the reference field.
func ByReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReference, opts...).ToFunc()
}

// ByLiveState orders the results by the live_state field.
func ByLiveState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiveState, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
