// Code generated by ent, DO NOT EDIT.

package servicelink

import (
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLTE(FieldID, id))
}

// Container applies equality check predicate on the "container" field. It's identical to ContainerEQ.
func Container(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldContainer, v))
}

// Reference applies equality check predicate on the "reference" field. It's identical to ReferenceEQ.
func Reference(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldReference, v))
}

// LiveState applies equality check predicate on the "live_state" field. It's identical to LiveStateEQ.
func LiveState(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldLiveState, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContainerEQ applies the EQ predicate on the "container" field.
func ContainerEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldContainer, v))
}

// ContainerNEQ applies the NEQ predicate on the "container" field.
func ContainerNEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldContainer, v))
}

// ContainerIn applies the In predicate on the "container" field.
func ContainerIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldContainer, vs...))
}

// ContainerNotIn applies the NotIn predicate on the "container" field.
func ContainerNotIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldContainer, vs...))
}

// ContainerGT applies the GT predicate on the "container" field.
func ContainerGT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGT(FieldContainer, v))
}

// ContainerGTE applies the GTE predicate on the "container" field.
func ContainerGTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGTE(FieldContainer, v))
}

// ContainerLT applies the LT predicate on the "container" field.
func ContainerLT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLT(FieldContainer, v))
}

// ContainerLTE applies the LTE predicate on the "container" field.
func ContainerLTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLTE(FieldContainer, v))
}

// ContainerContains applies the Contains predicate on the "container" field.
func ContainerContains(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContains(FieldContainer, v))
}

// ContainerHasPrefix applies the HasPrefix predicate on the "container" field.
func ContainerHasPrefix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasPrefix(FieldContainer, v))
}

// ContainerHasSuffix applies the HasSuffix predicate on the "container" field.
func ContainerHasSuffix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasSuffix(FieldContainer, v))
}

// ContainerEqualFold applies the EqualFold predicate on the "container" field.
func ContainerEqualFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEqualFold(FieldContainer, v))
}

// ContainerContainsFold applies the ContainsFold predicate on the "container" field.
func ContainerContainsFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContainsFold(FieldContainer, v))
}

// ServiceEQ applies the EQ predicate on the "service" field.
func ServiceEQ(v Service) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldService, v))
}

// ServiceNEQ applies the NEQ predicate on the "service" field.
func ServiceNEQ(v Service) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldService, v))
}

// ServiceIn applies the In predicate on the "service" field.
func ServiceIn(vs ...Service) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldService, vs...))
}

// ServiceNotIn applies the NotIn predicate on the "service" field.
func ServiceNotIn(vs ...Service) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldService, vs...))
}

// ReferenceEQ applies the EQ predicate on the "reference" field.
func ReferenceEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldReference, v))
}

// ReferenceNEQ applies the NEQ predicate on the "reference" field.
func ReferenceNEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldReference, v))
}

// ReferenceIn applies the In predicate on the "reference" field.
func ReferenceIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldReference, vs...))
}

// ReferenceNotIn applies the NotIn predicate on the "reference" field.
func ReferenceNotIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldReference, vs...))
}

// ReferenceGT applies the GT predicate on the "reference" field.
func ReferenceGT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGT(FieldReference, v))
}

// ReferenceGTE applies the GTE predicate on the "reference" field.
func ReferenceGTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGTE(FieldReference, v))
}

// ReferenceLT applies the LT predicate on the "reference" field.
func ReferenceLT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLT(FieldReference, v))
}

// ReferenceLTE applies the LTE predicate on the "reference" field.
func ReferenceLTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLTE(FieldReference, v))
}

// ReferenceContains applies the Contains predicate on the "reference" field.
func ReferenceContains(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContains(FieldReference, v))
}

// ReferenceHasPrefix applies the HasPrefix predicate on the "reference" field.
func ReferenceHasPrefix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasPrefix(FieldReference, v))
}

// ReferenceHasSuffix applies the HasSuffix predicate on the "reference" field.
func ReferenceHasSuffix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasSuffix(FieldReference, v))
}

// ReferenceEqualFold applies the EqualFold predicate on the "reference" field.
func ReferenceEqualFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEqualFold(FieldReference, v))
}

// ReferenceContainsFold applies the ContainsFold predicate on the "reference" field.
func ReferenceContainsFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContainsFold(FieldReference, v))
}

// LiveStateEQ applies the EQ predicate on the "live_state" field.
func LiveStateEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldLiveState, v))
}

// LiveStateNEQ applies the NEQ predicate on the "live_state" field.
func LiveStateNEQ(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldLiveState, v))
}

// LiveStateIn applies the In predicate on the "live_state" field.
func LiveStateIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldLiveState, vs...))
}

// LiveStateNotIn applies the NotIn predicate on the "live_state" field.
func LiveStateNotIn(vs ...string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldLiveState, vs...))
}

// LiveStateGT applies the GT predicate on the "live_state" field.
func LiveStateGT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGT(FieldLiveState, v))
}

// LiveStateGTE applies the GTE predicate on the "live_state" field.
func LiveStateGTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGTE(FieldLiveState, v))
}

// LiveStateLT applies the LT predicate on the "live_state" field.
func LiveStateLT(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLT(FieldLiveState, v))
}

// LiveStateLTE applies the LTE predicate on the "live_state" field.
func LiveStateLTE(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLTE(FieldLiveState, v))
}

// LiveStateContains applies the Contains predicate on the "live_state" field.
func LiveStateContains(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContains(FieldLiveState, v))
}

// LiveStateHasPrefix applies the HasPrefix predicate on the "live_state" field.
func LiveStateHasPrefix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasPrefix(FieldLiveState, v))
}

// LiveStateHasSuffix applies the HasSuffix predicate on the "live_state" field.
func LiveStateHasSuffix(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldHasSuffix(FieldLiveState, v))
}

// LiveStateIsNil applies the IsNil predicate on the "live_state" field.
func LiveStateIsNil() predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIsNull(FieldLiveState))
}

// LiveStateNotNil applies the NotNil predicate on the "live_state" field.
func LiveStateNotNil() predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotNull(FieldLiveState))
}

// LiveStateEqualFold applies the EqualFold predicate on the "live_state" field.
func LiveStateEqualFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEqualFold(FieldLiveState, v))
}

// LiveStateContainsFold applies the ContainsFold predicate on the "live_state" field.
func LiveStateContainsFold(v string) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldContainsFold(FieldLiveState, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ServiceLink {
	return predicate.ServiceLink(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceLink) predicate.ServiceLink {
	return predicate.ServiceLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceLink) predicate.ServiceLink {
	return predicate.ServiceLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceLink) predicate.ServiceLink {
	return predicate.ServiceLink(sql.NotPredicates(p))
}
