// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/metricsnapshot"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSnapshotCreate is the builder for creating a MetricSnapshot entity.
type MetricSnapshotCreate struct {
	config
	mutation *MetricSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRepoID sets the "repo_id" field.
func (_c *MetricSnapshotCreate) SetRepoID(v int) *MetricSnapshotCreate {
	_c.mutation.SetRepoID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *MetricSnapshotCreate) SetTimestamp(v time.Time) *MetricSnapshotCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetFeatCount sets the "feat_count" field.
func (_c *MetricSnapshotCreate) SetFeatCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetFeatCount(v)
	return _c
}

// SetNillableFeatCount sets the "feat_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableFeatCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetFeatCount(*v)
	}
	return _c
}

// SetFixCount sets the "fix_count" field.
func (_c *MetricSnapshotCreate) SetFixCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetFixCount(v)
	return _c
}

// SetNillableFixCount sets the "fix_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableFixCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetFixCount(*v)
	}
	return _c
}

// SetDocsCount sets the "docs_count" field.
func (_c *MetricSnapshotCreate) SetDocsCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetDocsCount(v)
	return _c
}

// SetNillableDocsCount sets the "docs_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableDocsCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetDocsCount(*v)
	}
	return _c
}

// SetChoreCount sets the "chore_count" field.
func (_c *MetricSnapshotCreate) SetChoreCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetChoreCount(v)
	return _c
}

// SetNillableChoreCount sets the "chore_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableChoreCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetChoreCount(*v)
	}
	return _c
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (_c *MetricSnapshotCreate) SetOtherCommitCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetOtherCommitCount(v)
	return _c
}

// SetNillableOtherCommitCount sets the "other_commit_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableOtherCommitCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetOtherCommitCount(*v)
	}
	return _c
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (_c *MetricSnapshotCreate) SetTotalCommitsFetched(v int) *MetricSnapshotCreate {
	_c.mutation.SetTotalCommitsFetched(v)
	return _c
}

// SetNillableTotalCommitsFetched sets the "total_commits_fetched" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableTotalCommitsFetched(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetTotalCommitsFetched(*v)
	}
	return _c
}

// SetReleaseCount sets the "release_count" field.
func (_c *MetricSnapshotCreate) SetReleaseCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetReleaseCount(v)
	return _c
}

// SetNillableReleaseCount sets the "release_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableReleaseCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetReleaseCount(*v)
	}
	return _c
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (_c *MetricSnapshotCreate) SetAvgLeadTimeHours(v float64) *MetricSnapshotCreate {
	_c.mutation.SetAvgLeadTimeHours(v)
	return _c
}

// SetNillableAvgLeadTimeHours sets the "avg_lead_time_hours" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableAvgLeadTimeHours(v *float64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetAvgLeadTimeHours(*v)
	}
	return _c
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (_c *MetricSnapshotCreate) SetWorkflowSuccessCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetWorkflowSuccessCount(v)
	return _c
}

// SetNillableWorkflowSuccessCount sets the "workflow_success_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableWorkflowSuccessCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetWorkflowSuccessCount(*v)
	}
	return _c
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (_c *MetricSnapshotCreate) SetWorkflowFailureCount(v int) *MetricSnapshotCreate {
	_c.mutation.SetWorkflowFailureCount(v)
	return _c
}

// SetNillableWorkflowFailureCount sets the "workflow_failure_count" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableWorkflowFailureCount(v *int) *MetricSnapshotCreate {
	if v != nil {
		_c.SetWorkflowFailureCount(*v)
	}
	return _c
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_c *MetricSnapshotCreate) SetWorkflowStatus(v string) *MetricSnapshotCreate {
	_c.mutation.SetWorkflowStatus(v)
	return _c
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableWorkflowStatus(v *string) *MetricSnapshotCreate {
	if v != nil {
		_c.SetWorkflowStatus(*v)
	}
	return _c
}

// Mutation returns the MetricSnapshotMutation object of the builder.
func (_c *MetricSnapshotCreate) Mutation() *MetricSnapshotMutation {
	return _c.mutation
}

// Save creates the MetricSnapshot in the database.
func (_c *MetricSnapshotCreate) Save(ctx context.Context) (*MetricSnapshot, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MetricSnapshotCreate) SaveX(ctx context.Context) *MetricSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetricSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetricSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MetricSnapshotCreate) check() error {
	if _, ok := _c.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "MetricSnapshot.repo_id"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "MetricSnapshot.timestamp"`)}
	}
	return nil
}

func (_c *MetricSnapshotCreate) sqlSave(ctx context.Context) (*MetricSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MetricSnapshotCreate) createSpec() (*MetricSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &MetricSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(metricsnapshot.Table, sqlgraph.NewFieldSpec(metricsnapshot.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RepoID(); ok {
		_spec.SetField(metricsnapshot.FieldRepoID, field.TypeInt, value)
		_node.RepoID = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(metricsnapshot.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.FeatCount(); ok {
		_spec.SetField(metricsnapshot.FieldFeatCount, field.TypeInt, value)
		_node.FeatCount = value
	}
	if value, ok := _c.mutation.FixCount(); ok {
		_spec.SetField(metricsnapshot.FieldFixCount, field.TypeInt, value)
		_node.FixCount = value
	}
	if value, ok := _c.mutation.DocsCount(); ok {
		_spec.SetField(metricsnapshot.FieldDocsCount, field.TypeInt, value)
		_node.DocsCount = value
	}
	if value, ok := _c.mutation.ChoreCount(); ok {
		_spec.SetField(metricsnapshot.FieldChoreCount, field.TypeInt, value)
		_node.ChoreCount = value
	}
	if value, ok := _c.mutation.OtherCommitCount(); ok {
		_spec.SetField(metricsnapshot.FieldOtherCommitCount, field.TypeInt, value)
		_node.OtherCommitCount = value
	}
	if value, ok := _c.mutation.TotalCommitsFetched(); ok {
		_spec.SetField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt, value)
		_node.TotalCommitsFetched = value
	}
	if value, ok := _c.mutation.ReleaseCount(); ok {
		_spec.SetField(metricsnapshot.FieldReleaseCount, field.TypeInt, value)
		_node.ReleaseCount = value
	}
	if value, ok := _c.mutation.AvgLeadTimeHours(); ok {
		_spec.SetField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64, value)
		_node.AvgLeadTimeHours = value
	}
	if value, ok := _c.mutation.WorkflowSuccessCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt, value)
		_node.WorkflowSuccessCount = value
	}
	if value, ok := _c.mutation.WorkflowFailureCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt, value)
		_node.WorkflowFailureCount = value
	}
	if value, ok := _c.mutation.WorkflowStatus(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowStatus, field.TypeString, value)
		_node.WorkflowStatus = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetricSnapshot.Create().
//		SetRepoID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetricSnapshotUpsert) {
//			SetRepoID(v+v).
//		}).
//		Exec(ctx)
func (_c *MetricSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *MetricSnapshotUpsertOne {
	_c.conflict = opts
	return &MetricSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MetricSnapshotCreate) OnConflictColumns(columns ...string) *MetricSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MetricSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// MetricSnapshotUpsertOne is the builder for "upsert"-ing
	//  one MetricSnapshot node.
	MetricSnapshotUpsertOne struct {
		create *MetricSnapshotCreate
	}

	// MetricSnapshotUpsert is the "OnConflict" setter.
	MetricSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetRepoID sets the "repo_id" field.
func (u *MetricSnapshotUpsert) SetRepoID(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldRepoID, v)
	return u
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateRepoID() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldRepoID)
	return u
}

// AddRepoID adds v to the "repo_id" field.
func (u *MetricSnapshotUpsert) AddRepoID(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldRepoID, v)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *MetricSnapshotUpsert) SetTimestamp(v time.Time) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateTimestamp() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldTimestamp)
	return u
}

// SetFeatCount sets the "feat_count" field.
func (u *MetricSnapshotUpsert) SetFeatCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldFeatCount, v)
	return u
}

// UpdateFeatCount sets the "feat_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateFeatCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldFeatCount)
	return u
}

// AddFeatCount adds v to the "feat_count" field.
func (u *MetricSnapshotUpsert) AddFeatCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldFeatCount, v)
	return u
}

// ClearFeatCount clears the value of the "feat_count" field.
func (u *MetricSnapshotUpsert) ClearFeatCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldFeatCount)
	return u
}

// SetFixCount sets the "fix_count" field.
func (u *MetricSnapshotUpsert) SetFixCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldFixCount, v)
	return u
}

// UpdateFixCount sets the "fix_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateFixCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldFixCount)
	return u
}

// AddFixCount adds v to the "fix_count" field.
func (u *MetricSnapshotUpsert) AddFixCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldFixCount, v)
	return u
}

// ClearFixCount clears the value of the "fix_count" field.
func (u *MetricSnapshotUpsert) ClearFixCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldFixCount)
	return u
}

// SetDocsCount sets the "docs_count" field.
func (u *MetricSnapshotUpsert) SetDocsCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldDocsCount, v)
	return u
}

// UpdateDocsCount sets the "docs_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateDocsCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldDocsCount)
	return u
}

// AddDocsCount adds v to the "docs_count" field.
func (u *MetricSnapshotUpsert) AddDocsCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldDocsCount, v)
	return u
}

// ClearDocsCount clears the value of the "docs_count" field.
func (u *MetricSnapshotUpsert) ClearDocsCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldDocsCount)
	return u
}

// SetChoreCount sets the "chore_count" field.
func (u *MetricSnapshotUpsert) SetChoreCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldChoreCount, v)
	return u
}

// UpdateChoreCount sets the "chore_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateChoreCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldChoreCount)
	return u
}

// AddChoreCount adds v to the "chore_count" field.
func (u *MetricSnapshotUpsert) AddChoreCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldChoreCount, v)
	return u
}

// ClearChoreCount clears the value of the "chore_count" field.
func (u *MetricSnapshotUpsert) ClearChoreCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldChoreCount)
	return u
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (u *MetricSnapshotUpsert) SetOtherCommitCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldOtherCommitCount, v)
	return u
}

// UpdateOtherCommitCount sets the "other_commit_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateOtherCommitCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldOtherCommitCount)
	return u
}

// AddOtherCommitCount adds v to the "other_commit_count" field.
func (u *MetricSnapshotUpsert) AddOtherCommitCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldOtherCommitCount, v)
	return u
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (u *MetricSnapshotUpsert) ClearOtherCommitCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldOtherCommitCount)
	return u
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (u *MetricSnapshotUpsert) SetTotalCommitsFetched(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldTotalCommitsFetched, v)
	return u
}

// UpdateTotalCommitsFetched sets the "total_commits_fetched" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateTotalCommitsFetched() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldTotalCommitsFetched)
	return u
}

// AddTotalCommitsFetched adds v to the "total_commits_fetched" field.
func (u *MetricSnapshotUpsert) AddTotalCommitsFetched(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldTotalCommitsFetched, v)
	return u
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (u *MetricSnapshotUpsert) ClearTotalCommitsFetched() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldTotalCommitsFetched)
	return u
}

// SetReleaseCount sets the "release_count" field.
func (u *MetricSnapshotUpsert) SetReleaseCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldReleaseCount, v)
	return u
}

// UpdateReleaseCount sets the "release_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateReleaseCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldReleaseCount)
	return u
}

// AddReleaseCount adds v to the "release_count" field.
func (u *MetricSnapshotUpsert) AddReleaseCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldReleaseCount, v)
	return u
}

// ClearReleaseCount clears the value of the "release_count" field.
func (u *MetricSnapshotUpsert) ClearReleaseCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldReleaseCount)
	return u
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsert) SetAvgLeadTimeHours(v float64) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldAvgLeadTimeHours, v)
	return u
}

// UpdateAvgLeadTimeHours sets the "avg_lead_time_hours" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateAvgLeadTimeHours() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldAvgLeadTimeHours)
	return u
}

// AddAvgLeadTimeHours adds v to the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsert) AddAvgLeadTimeHours(v float64) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldAvgLeadTimeHours, v)
	return u
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsert) ClearAvgLeadTimeHours() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldAvgLeadTimeHours)
	return u
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (u *MetricSnapshotUpsert) SetWorkflowSuccessCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldWorkflowSuccessCount, v)
	return u
}

// UpdateWorkflowSuccessCount sets the "workflow_success_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateWorkflowSuccessCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldWorkflowSuccessCount)
	return u
}

// AddWorkflowSuccessCount adds v to the "workflow_success_count" field.
func (u *MetricSnapshotUpsert) AddWorkflowSuccessCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldWorkflowSuccessCount, v)
	return u
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (u *MetricSnapshotUpsert) ClearWorkflowSuccessCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldWorkflowSuccessCount)
	return u
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (u *MetricSnapshotUpsert) SetWorkflowFailureCount(v int) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldWorkflowFailureCount, v)
	return u
}

// UpdateWorkflowFailureCount sets the "workflow_failure_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateWorkflowFailureCount() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldWorkflowFailureCount)
	return u
}

// AddWorkflowFailureCount adds v to the "workflow_failure_count" field.
func (u *MetricSnapshotUpsert) AddWorkflowFailureCount(v int) *MetricSnapshotUpsert {
	u.Add(metricsnapshot.FieldWorkflowFailureCount, v)
	return u
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (u *MetricSnapshotUpsert) ClearWorkflowFailureCount() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldWorkflowFailureCount)
	return u
}

// SetWorkflowStatus sets the "workflow_status" field.
func (u *MetricSnapshotUpsert) SetWorkflowStatus(v string) *MetricSnapshotUpsert {
	u.Set(metricsnapshot.FieldWorkflowStatus, v)
	return u
}

// UpdateWorkflowStatus sets the "workflow_status" field to the value that was provided on create.
func (u *MetricSnapshotUpsert) UpdateWorkflowStatus() *MetricSnapshotUpsert {
	u.SetExcluded(metricsnapshot.FieldWorkflowStatus)
	return u
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (u *MetricSnapshotUpsert) ClearWorkflowStatus() *MetricSnapshotUpsert {
	u.SetNull(metricsnapshot.FieldWorkflowStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetricSnapshotUpsertOne) UpdateNewValues() *MetricSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MetricSnapshotUpsertOne) Ignore() *MetricSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetricSnapshotUpsertOne) DoNothing() *MetricSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetricSnapshotCreate.OnConflict
// documentation for more info.
func (u *MetricSnapshotUpsertOne) Update(set func(*MetricSnapshotUpsert)) *MetricSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetricSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetRepoID sets the "repo_id" field.
func (u *MetricSnapshotUpsertOne) SetRepoID(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetRepoID(v)
	})
}

// AddRepoID adds v to the "repo_id" field.
func (u *MetricSnapshotUpsertOne) AddRepoID(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateRepoID() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateRepoID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *MetricSnapshotUpsertOne) SetTimestamp(v time.Time) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateTimestamp() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateTimestamp()
	})
}

// SetFeatCount sets the "feat_count" field.
func (u *MetricSnapshotUpsertOne) SetFeatCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetFeatCount(v)
	})
}

// AddFeatCount adds v to the "feat_count" field.
func (u *MetricSnapshotUpsertOne) AddFeatCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddFeatCount(v)
	})
}

// UpdateFeatCount sets the "feat_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateFeatCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateFeatCount()
	})
}

// ClearFeatCount clears the value of the "feat_count" field.
func (u *MetricSnapshotUpsertOne) ClearFeatCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearFeatCount()
	})
}

// SetFixCount sets the "fix_count" field.
func (u *MetricSnapshotUpsertOne) SetFixCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetFixCount(v)
	})
}

// AddFixCount adds v to the "fix_count" field.
func (u *MetricSnapshotUpsertOne) AddFixCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddFixCount(v)
	})
}

// UpdateFixCount sets the "fix_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateFixCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateFixCount()
	})
}

// ClearFixCount clears the value of the "fix_count" field.
func (u *MetricSnapshotUpsertOne) ClearFixCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearFixCount()
	})
}

// SetDocsCount sets the "docs_count" field.
func (u *MetricSnapshotUpsertOne) SetDocsCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetDocsCount(v)
	})
}

// AddDocsCount adds v to the "docs_count" field.
func (u *MetricSnapshotUpsertOne) AddDocsCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddDocsCount(v)
	})
}

// UpdateDocsCount sets the "docs_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateDocsCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateDocsCount()
	})
}

// ClearDocsCount clears the value of the "docs_count" field.
func (u *MetricSnapshotUpsertOne) ClearDocsCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearDocsCount()
	})
}

// SetChoreCount sets the "chore_count" field.
func (u *MetricSnapshotUpsertOne) SetChoreCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetChoreCount(v)
	})
}

// AddChoreCount adds v to the "chore_count" field.
func (u *MetricSnapshotUpsertOne) AddChoreCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddChoreCount(v)
	})
}

// UpdateChoreCount sets the "chore_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateChoreCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateChoreCount()
	})
}

// ClearChoreCount clears the value of the "chore_count" field.
func (u *MetricSnapshotUpsertOne) ClearChoreCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearChoreCount()
	})
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (u *MetricSnapshotUpsertOne) SetOtherCommitCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetOtherCommitCount(v)
	})
}

// AddOtherCommitCount adds v to the "other_commit_count" field.
func (u *MetricSnapshotUpsertOne) AddOtherCommitCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddOtherCommitCount(v)
	})
}

// UpdateOtherCommitCount sets the "other_commit_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateOtherCommitCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateOtherCommitCount()
	})
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (u *MetricSnapshotUpsertOne) ClearOtherCommitCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearOtherCommitCount()
	})
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertOne) SetTotalCommitsFetched(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetTotalCommitsFetched(v)
	})
}

// AddTotalCommitsFetched adds v to the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertOne) AddTotalCommitsFetched(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddTotalCommitsFetched(v)
	})
}

// UpdateTotalCommitsFetched sets the "total_commits_fetched" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateTotalCommitsFetched() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateTotalCommitsFetched()
	})
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertOne) ClearTotalCommitsFetched() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearTotalCommitsFetched()
	})
}

// SetReleaseCount sets the "release_count" field.
func (u *MetricSnapshotUpsertOne) SetReleaseCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetReleaseCount(v)
	})
}

// AddReleaseCount adds v to the "release_count" field.
func (u *MetricSnapshotUpsertOne) AddReleaseCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddReleaseCount(v)
	})
}

// UpdateReleaseCount sets the "release_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateReleaseCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateReleaseCount()
	})
}

// ClearReleaseCount clears the value of the "release_count" field.
func (u *MetricSnapshotUpsertOne) ClearReleaseCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearReleaseCount()
	})
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertOne) SetAvgLeadTimeHours(v float64) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetAvgLeadTimeHours(v)
	})
}

// AddAvgLeadTimeHours adds v to the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertOne) AddAvgLeadTimeHours(v float64) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddAvgLeadTimeHours(v)
	})
}

// UpdateAvgLeadTimeHours sets the "avg_lead_time_hours" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateAvgLeadTimeHours() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateAvgLeadTimeHours()
	})
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertOne) ClearAvgLeadTimeHours() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearAvgLeadTimeHours()
	})
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (u *MetricSnapshotUpsertOne) SetWorkflowSuccessCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowSuccessCount(v)
	})
}

// AddWorkflowSuccessCount adds v to the "workflow_success_count" field.
func (u *MetricSnapshotUpsertOne) AddWorkflowSuccessCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddWorkflowSuccessCount(v)
	})
}

// UpdateWorkflowSuccessCount sets the "workflow_success_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateWorkflowSuccessCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowSuccessCount()
	})
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (u *MetricSnapshotUpsertOne) ClearWorkflowSuccessCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowSuccessCount()
	})
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertOne) SetWorkflowFailureCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowFailureCount(v)
	})
}

// AddWorkflowFailureCount adds v to the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertOne) AddWorkflowFailureCount(v int) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddWorkflowFailureCount(v)
	})
}

// UpdateWorkflowFailureCount sets the "workflow_failure_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateWorkflowFailureCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowFailureCount()
	})
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertOne) ClearWorkflowFailureCount() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowFailureCount()
	})
}

// SetWorkflowStatus sets the "workflow_status" field.
func (u *MetricSnapshotUpsertOne) SetWorkflowStatus(v string) *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowStatus(v)
	})
}

// UpdateWorkflowStatus sets the "workflow_status" field to the value that was provided on create.
func (u *MetricSnapshotUpsertOne) UpdateWorkflowStatus() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowStatus()
	})
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (u *MetricSnapshotUpsertOne) ClearWorkflowStatus() *MetricSnapshotUpsertOne {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowStatus()
	})
}

// Exec executes the query.
func (u *MetricSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetricSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetricSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MetricSnapshotUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MetricSnapshotUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MetricSnapshotCreateBulk is the builder for creating many MetricSnapshot entities in bulk.
type MetricSnapshotCreateBulk struct {
	config
	err      error
	builders []*MetricSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the MetricSnapshot entities in the database.
func (_c *MetricSnapshotCreateBulk) Save(ctx context.Context) ([]*MetricSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MetricSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MetricSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MetricSnapshotCreateBulk) SaveX(ctx context.Context) []*MetricSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetricSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetricSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetricSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetricSnapshotUpsert) {
//			SetRepoID(v+v).
//		}).
//		Exec(ctx)
func (_c *MetricSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *MetricSnapshotUpsertBulk {
	_c.conflict = opts
	return &MetricSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MetricSnapshotCreateBulk) OnConflictColumns(columns ...string) *MetricSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MetricSnapshotUpsertBulk{
		create: _c,
	}
}

// MetricSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of MetricSnapshot nodes.
type MetricSnapshotUpsertBulk struct {
	create *MetricSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetricSnapshotUpsertBulk) UpdateNewValues() *MetricSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetricSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MetricSnapshotUpsertBulk) Ignore() *MetricSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetricSnapshotUpsertBulk) DoNothing() *MetricSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetricSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *MetricSnapshotUpsertBulk) Update(set func(*MetricSnapshotUpsert)) *MetricSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetricSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetRepoID sets the "repo_id" field.
func (u *MetricSnapshotUpsertBulk) SetRepoID(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetRepoID(v)
	})
}

// AddRepoID adds v to the "repo_id" field.
func (u *MetricSnapshotUpsertBulk) AddRepoID(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddRepoID(v)
	})
}

// UpdateRepoID sets the "repo_id" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateRepoID() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateRepoID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *MetricSnapshotUpsertBulk) SetTimestamp(v time.Time) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateTimestamp() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateTimestamp()
	})
}

// SetFeatCount sets the "feat_count" field.
func (u *MetricSnapshotUpsertBulk) SetFeatCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetFeatCount(v)
	})
}

// AddFeatCount adds v to the "feat_count" field.
func (u *MetricSnapshotUpsertBulk) AddFeatCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddFeatCount(v)
	})
}

// UpdateFeatCount sets the "feat_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateFeatCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateFeatCount()
	})
}

// ClearFeatCount clears the value of the "feat_count" field.
func (u *MetricSnapshotUpsertBulk) ClearFeatCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearFeatCount()
	})
}

// SetFixCount sets the "fix_count" field.
func (u *MetricSnapshotUpsertBulk) SetFixCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetFixCount(v)
	})
}

// AddFixCount adds v to the "fix_count" field.
func (u *MetricSnapshotUpsertBulk) AddFixCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddFixCount(v)
	})
}

// UpdateFixCount sets the "fix_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateFixCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateFixCount()
	})
}

// ClearFixCount clears the value of the "fix_count" field.
func (u *MetricSnapshotUpsertBulk) ClearFixCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearFixCount()
	})
}

// SetDocsCount sets the "docs_count" field.
func (u *MetricSnapshotUpsertBulk) SetDocsCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetDocsCount(v)
	})
}

// AddDocsCount adds v to the "docs_count" field.
func (u *MetricSnapshotUpsertBulk) AddDocsCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddDocsCount(v)
	})
}

// UpdateDocsCount sets the "docs_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateDocsCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateDocsCount()
	})
}

// ClearDocsCount clears the value of the "docs_count" field.
func (u *MetricSnapshotUpsertBulk) ClearDocsCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearDocsCount()
	})
}

// SetChoreCount sets the "chore_count" field.
func (u *MetricSnapshotUpsertBulk) SetChoreCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetChoreCount(v)
	})
}

// AddChoreCount adds v to the "chore_count" field.
func (u *MetricSnapshotUpsertBulk) AddChoreCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddChoreCount(v)
	})
}

// UpdateChoreCount sets the "chore_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateChoreCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateChoreCount()
	})
}

// ClearChoreCount clears the value of the "chore_count" field.
func (u *MetricSnapshotUpsertBulk) ClearChoreCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearChoreCount()
	})
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (u *MetricSnapshotUpsertBulk) SetOtherCommitCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetOtherCommitCount(v)
	})
}

// AddOtherCommitCount adds v to the "other_commit_count" field.
func (u *MetricSnapshotUpsertBulk) AddOtherCommitCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddOtherCommitCount(v)
	})
}

// UpdateOtherCommitCount sets the "other_commit_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateOtherCommitCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateOtherCommitCount()
	})
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (u *MetricSnapshotUpsertBulk) ClearOtherCommitCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearOtherCommitCount()
	})
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertBulk) SetTotalCommitsFetched(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetTotalCommitsFetched(v)
	})
}

// AddTotalCommitsFetched adds v to the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertBulk) AddTotalCommitsFetched(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddTotalCommitsFetched(v)
	})
}

// UpdateTotalCommitsFetched sets the "total_commits_fetched" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateTotalCommitsFetched() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateTotalCommitsFetched()
	})
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (u *MetricSnapshotUpsertBulk) ClearTotalCommitsFetched() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearTotalCommitsFetched()
	})
}

// SetReleaseCount sets the "release_count" field.
func (u *MetricSnapshotUpsertBulk) SetReleaseCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetReleaseCount(v)
	})
}

// AddReleaseCount adds v to the "release_count" field.
func (u *MetricSnapshotUpsertBulk) AddReleaseCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddReleaseCount(v)
	})
}

// UpdateReleaseCount sets the "release_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateReleaseCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateReleaseCount()
	})
}

// ClearReleaseCount clears the value of the "release_count" field.
func (u *MetricSnapshotUpsertBulk) ClearReleaseCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearReleaseCount()
	})
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertBulk) SetAvgLeadTimeHours(v float64) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetAvgLeadTimeHours(v)
	})
}

// AddAvgLeadTimeHours adds v to the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertBulk) AddAvgLeadTimeHours(v float64) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddAvgLeadTimeHours(v)
	})
}

// UpdateAvgLeadTimeHours sets the "avg_lead_time_hours" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateAvgLeadTimeHours() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateAvgLeadTimeHours()
	})
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (u *MetricSnapshotUpsertBulk) ClearAvgLeadTimeHours() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearAvgLeadTimeHours()
	})
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (u *MetricSnapshotUpsertBulk) SetWorkflowSuccessCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowSuccessCount(v)
	})
}

// AddWorkflowSuccessCount adds v to the "workflow_success_count" field.
func (u *MetricSnapshotUpsertBulk) AddWorkflowSuccessCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddWorkflowSuccessCount(v)
	})
}

// UpdateWorkflowSuccessCount sets the "workflow_success_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateWorkflowSuccessCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowSuccessCount()
	})
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (u *MetricSnapshotUpsertBulk) ClearWorkflowSuccessCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowSuccessCount()
	})
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertBulk) SetWorkflowFailureCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowFailureCount(v)
	})
}

// AddWorkflowFailureCount adds v to the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertBulk) AddWorkflowFailureCount(v int) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.AddWorkflowFailureCount(v)
	})
}

// UpdateWorkflowFailureCount sets the "workflow_failure_count" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateWorkflowFailureCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowFailureCount()
	})
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (u *MetricSnapshotUpsertBulk) ClearWorkflowFailureCount() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowFailureCount()
	})
}

// SetWorkflowStatus sets the "workflow_status" field.
func (u *MetricSnapshotUpsertBulk) SetWorkflowStatus(v string) *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.SetWorkflowStatus(v)
	})
}

// UpdateWorkflowStatus sets the "workflow_status" field to the value that was provided on create.
func (u *MetricSnapshotUpsertBulk) UpdateWorkflowStatus() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.UpdateWorkflowStatus()
	})
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (u *MetricSnapshotUpsertBulk) ClearWorkflowStatus() *MetricSnapshotUpsertBulk {
	return u.Update(func(s *MetricSnapshotUpsert) {
		s.ClearWorkflowStatus()
	})
}

// Exec executes the query.
func (u *MetricSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MetricSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetricSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetricSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
