// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/predicate"
	"gitlens/ent/servicelink"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceLinkUpdate is the builder for updating ServiceLink entities.
type ServiceLinkUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceLinkMutation
}

// Where appends a list predicates to the ServiceLinkUpdate builder.
func (_u *ServiceLinkUpdate) Where(ps ...predicate.ServiceLink) *ServiceLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContainer sets the "container" field.
func (_u *ServiceLinkUpdate) SetContainer(v string) *ServiceLinkUpdate {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableContainer(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetService sets the "service" field.
func (_u *ServiceLinkUpdate) SetService(v servicelink.Service) *ServiceLinkUpdate {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableService(v *servicelink.Service) *ServiceLinkUpdate {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetReference sets the "reference" field.
func (_u *ServiceLinkUpdate) SetReference(v string) *ServiceLinkUpdate {
	_u.mutation.SetReference(v)
	return _u
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableReference(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetReference(*v)
	}
	return _u
}

// SetLiveState sets the "live_state" field.
func (_u *ServiceLinkUpdate) SetLiveState(v string) *ServiceLinkUpdate {
	_u.mutation.SetLiveState(v)
	return _u
}

// SetNillableLiveState sets the "live_state" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableLiveState(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetLiveState(*v)
	}
	return _u
}

// ClearLiveState clears the value of the "live_state" field.
func (_u *ServiceLinkUpdate) ClearLiveState() *ServiceLinkUpdate {
	_u.mutation.ClearLiveState()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceLinkUpdate) SetUpdatedAt(v time.Time) *ServiceLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ServiceLinkMutation object of the builder.
func (_u *ServiceLinkUpdate) Mutation() *ServiceLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceLinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceLinkUpdate) check() error {
	if v, ok := _u.mutation.Service(); ok {
		if err := servicelink.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "ServiceLink.service": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicelink.Table, servicelink.Columns, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(servicelink.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(servicelink.FieldService, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Reference(); ok {
		_spec.SetField(servicelink.FieldReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.LiveState(); ok {
		_spec.SetField(servicelink.FieldLiveState, field.TypeString, value)
	}
	if _u.mutation.LiveStateCleared() {
		_spec.ClearField(servicelink.FieldLiveState, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicelink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceLinkUpdateOne is the builder for updating a single ServiceLink entity.
type ServiceLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceLinkMutation
}

// SetContainer sets the "container" field.
func (_u *ServiceLinkUpdateOne) SetContainer(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetContainer(v)
	return _u
}

// SetNillableContainer sets the "container" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableContainer(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetContainer(*v)
	}
	return _u
}

// SetService sets the "service" field.
func (_u *ServiceLinkUpdateOne) SetService(v servicelink.Service) *ServiceLinkUpdateOne {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableService(v *servicelink.Service) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetReference sets the "reference" field.
func (_u *ServiceLinkUpdateOne) SetReference(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetReference(v)
	return _u
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableReference(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetReference(*v)
	}
	return _u
}

// SetLiveState sets the "live_state" field.
func (_u *ServiceLinkUpdateOne) SetLiveState(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetLiveState(v)
	return _u
}

// SetNillableLiveState sets the "live_state" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableLiveState(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetLiveState(*v)
	}
	return _u
}

// ClearLiveState clears the value of the "live_state" field.
func (_u *ServiceLinkUpdateOne) ClearLiveState() *ServiceLinkUpdateOne {
	_u.mutation.ClearLiveState()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceLinkUpdateOne) SetUpdatedAt(v time.Time) *ServiceLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ServiceLinkMutation object of the builder.
func (_u *ServiceLinkUpdateOne) Mutation() *ServiceLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServiceLinkUpdate builder.
func (_u *ServiceLinkUpdateOne) Where(ps ...predicate.ServiceLink) *ServiceLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceLinkUpdateOne) Select(field string, fields ...string) *ServiceLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceLink entity.
func (_u *ServiceLinkUpdateOne) Save(ctx context.Context) (*ServiceLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceLinkUpdateOne) SaveX(ctx context.Context) *ServiceLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Service(); ok {
		if err := servicelink.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "ServiceLink.service": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceLinkUpdateOne) sqlSave(ctx context.Context) (_node *ServiceLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicelink.Table, servicelink.Columns, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicelink.FieldID)
		for _, f := range fields {
			if !servicelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servicelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Container(); ok {
		_spec.SetField(servicelink.FieldContainer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(servicelink.FieldService, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Reference(); ok {
		_spec.SetField(servicelink.FieldReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.LiveState(); ok {
		_spec.SetField(servicelink.FieldLiveState, field.TypeString, value)
	}
	if _u.mutation.LiveStateCleared() {
		_spec.ClearField(servicelink.FieldLiveState, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicelink.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ServiceLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
