// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gitlens/ent/servicelink"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServiceLink is the model entity for the ServiceLink schema.
type ServiceLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Container holds the value of the "container" field.
	Container string `json:"container,omitempty"`
	// Service holds the value of the "service" field.
	Service servicelink.Service `json:"service,omitempty"`
	// Reference holds the value of the "reference" field.
	Reference string `json:"reference,omitempty"`
	// LiveState holds the value of the "live_state" field.
	LiveState string `json:"live_state,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servicelink.FieldID:
			values[i] = new(sql.NullInt64)
		case servicelink.FieldContainer, servicelink.FieldService, servicelink.FieldReference, servicelink.FieldLiveState:
			values[i] = new(sql.NullString)
		case servicelink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceLink fields.
func (_m *ServiceLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servicelink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case servicelink.FieldContainer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container", values[i])
			} else if value.Valid {
				_m.Container = value.String
			}
		case servicelink.FieldService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service", values[i])
			} else if value.Valid {
				_m.Service = servicelink.Service(value.String)
			}
		case servicelink.FieldReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference", values[i])
			} else if value.Valid {
				_m.Reference = value.String
			}
		case servicelink.FieldLiveState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field live_state", values[i])
			} else if value.Valid {
				_m.LiveState = value.String
			}
		case servicelink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServiceLink.
// This includes values selected through modifiers, order, etc.
func (_m *ServiceLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ServiceLink.
// Note that you need to call ServiceLink.Unwrap() before calling this method if this ServiceLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServiceLink) Update() *ServiceLinkUpdateOne {
	return NewServiceLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServiceLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServiceLink) Unwrap() *ServiceLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServiceLink) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("container=")
	builder.WriteString(_m.Container)
	builder.WriteString(", ")
	builder.WriteString("service=")
	builder.WriteString(fmt.Sprintf("%v", _m.Service))
	builder.WriteString(", ")
	builder.WriteString("reference=")
	builder.WriteString(_m.Reference)
	builder.WriteString(", ")
	builder.WriteString("live_state=")
	builder.WriteString(_m.LiveState)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ServiceLinks is a parsable slice of ServiceLink.
type ServiceLinks []*ServiceLink
