// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/servicelink"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceLinkCreate is the builder for creating a ServiceLink entity.
type ServiceLinkCreate struct {
	config
	mutation *ServiceLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContainer sets the "container" field.
func (_c *ServiceLinkCreate) SetContainer(v string) *ServiceLinkCreate {
	_c.mutation.SetContainer(v)
	return _c
}

// SetService sets the "service" field.
func (_c *ServiceLinkCreate) SetService(v servicelink.Service) *ServiceLinkCreate {
	_c.mutation.SetService(v)
	return _c
}

// SetReference sets the "reference" field.
func (_c *ServiceLinkCreate) SetReference(v string) *ServiceLinkCreate {
	_c.mutation.SetReference(v)
	return _c
}

// SetLiveState sets the "live_state" field.
func (_c *ServiceLinkCreate) SetLiveState(v string) *ServiceLinkCreate {
	_c.mutation.SetLiveState(v)
	return _c
}

// SetNillableLiveState sets the "live_state" field if the given value is not nil.
func (_c *ServiceLinkCreate) SetNillableLiveState(v *string) *ServiceLinkCreate {
	if v != nil {
		_c.SetLiveState(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ServiceLinkCreate) SetUpdatedAt(v time.Time) *ServiceLinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ServiceLinkCreate) SetNillableUpdatedAt(v *time.Time) *ServiceLinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ServiceLinkMutation object of the builder.
func (_c *ServiceLinkCreate) Mutation() *ServiceLinkMutation {
	return _c.mutation
}

// Save creates the ServiceLink in the database.
func (_c *ServiceLinkCreate) Save(ctx context.Context) (*ServiceLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServiceLinkCreate) SaveX(ctx context.Context) *ServiceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServiceLinkCreate) defaults() {
	if _, ok := _c.mutation.LiveState(); !ok {
		v := servicelink.DefaultLiveState
		_c.mutation.SetLiveState(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := servicelink.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServiceLinkCreate) check() error {
	if _, ok := _c.mutation.Container(); !ok {
		return &ValidationError{Name: "container", err: errors.New(`ent: missing required field "ServiceLink.container"`)}
	}
	if _, ok := _c.mutation.Service(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required field "ServiceLink.service"`)}
	}
	if v, ok := _c.mutation.Service(); ok {
		if err := servicelink.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "ServiceLink.service": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reference(); !ok {
		return &ValidationError{Name: "reference", err: errors.New(`ent: missing required field "ServiceLink.reference"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ServiceLink.updated_at"`)}
	}
	return nil
}

func (_c *ServiceLinkCreate) sqlSave(ctx context.Context) (*ServiceLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServiceLinkCreate) createSpec() (*ServiceLink, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(servicelink.Table, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Container(); ok {
		_spec.SetField(servicelink.FieldContainer, field.TypeString, value)
		_node.Container = value
	}
	if value, ok := _c.mutation.Service(); ok {
		_spec.SetField(servicelink.FieldService, field.TypeEnum, value)
		_node.Service = value
	}
	if value, ok := _c.mutation.Reference(); ok {
		_spec.SetField(servicelink.FieldReference, field.TypeString, value)
		_node.Reference = value
	}
	if value, ok := _c.mutation.LiveState(); ok {
		_spec.SetField(servicelink.FieldLiveState, field.TypeString, value)
		_node.LiveState = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(servicelink.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceLink.Create().
//		SetContainer(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceLinkUpsert) {
//			SetContainer(v+v).
//		}).
//		Exec(ctx)
func (_c *ServiceLinkCreate) OnConflict(opts ...sql.ConflictOption) *ServiceLinkUpsertOne {
	_c.conflict = opts
	return &ServiceLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServiceLinkCreate) OnConflictColumns(columns ...string) *ServiceLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServiceLinkUpsertOne{
		create: _c,
	}
}

type (
	// ServiceLinkUpsertOne is the builder for "upsert"-ing
	//  one ServiceLink node.
	ServiceLinkUpsertOne struct {
		create *ServiceLinkCreate
	}

	// ServiceLinkUpsert is the "OnConflict" setter.
	ServiceLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetContainer sets the "container" field.
func (u *ServiceLinkUpsert) SetContainer(v string) *ServiceLinkUpsert {
	u.Set(servicelink.FieldContainer, v)
	return u
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ServiceLinkUpsert) UpdateContainer() *ServiceLinkUpsert {
	u.SetExcluded(servicelink.FieldContainer)
	return u
}

// SetService sets the "service" field.
func (u *ServiceLinkUpsert) SetService(v servicelink.Service) *ServiceLinkUpsert {
	u.Set(servicelink.FieldService, v)
	return u
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ServiceLinkUpsert) UpdateService() *ServiceLinkUpsert {
	u.SetExcluded(servicelink.FieldService)
	return u
}

// SetReference sets the "reference" field.
func (u *ServiceLinkUpsert) SetReference(v string) *ServiceLinkUpsert {
	u.Set(servicelink.FieldReference, v)
	return u
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *ServiceLinkUpsert) UpdateReference() *ServiceLinkUpsert {
	u.SetExcluded(servicelink.FieldReference)
	return u
}

// SetLiveState sets the "live_state" field.
func (u *ServiceLinkUpsert) SetLiveState(v string) *ServiceLinkUpsert {
	u.Set(servicelink.FieldLiveState, v)
	return u
}

// UpdateLiveState sets the "live_state" field to the value that was provided on create.
func (u *ServiceLinkUpsert) UpdateLiveState() *ServiceLinkUpsert {
	u.SetExcluded(servicelink.FieldLiveState)
	return u
}

// ClearLiveState clears the value of the "live_state" field.
func (u *ServiceLinkUpsert) ClearLiveState() *ServiceLinkUpsert {
	u.SetNull(servicelink.FieldLiveState)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceLinkUpsert) SetUpdatedAt(v time.Time) *ServiceLinkUpsert {
	u.Set(servicelink.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceLinkUpsert) UpdateUpdatedAt() *ServiceLinkUpsert {
	u.SetExcluded(servicelink.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ServiceLinkUpsertOne) UpdateNewValues() *ServiceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ServiceLinkUpsertOne) Ignore() *ServiceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceLinkUpsertOne) DoNothing() *ServiceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceLinkCreate.OnConflict
// documentation for more info.
func (u *ServiceLinkUpsertOne) Update(set func(*ServiceLinkUpsert)) *ServiceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetContainer sets the "container" field.
func (u *ServiceLinkUpsertOne) SetContainer(v string) *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetContainer(v)
	})
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ServiceLinkUpsertOne) UpdateContainer() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateContainer()
	})
}

// SetService sets the "service" field.
func (u *ServiceLinkUpsertOne) SetService(v servicelink.Service) *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetService(v)
	})
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ServiceLinkUpsertOne) UpdateService() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateService()
	})
}

// SetReference sets the "reference" field.
func (u *ServiceLinkUpsertOne) SetReference(v string) *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetReference(v)
	})
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *ServiceLinkUpsertOne) UpdateReference() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateReference()
	})
}

// SetLiveState sets the "live_state" field.
func (u *ServiceLinkUpsertOne) SetLiveState(v string) *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetLiveState(v)
	})
}

// UpdateLiveState sets the "live_state" field to the value that was provided on create.
func (u *ServiceLinkUpsertOne) UpdateLiveState() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateLiveState()
	})
}

// ClearLiveState clears the value of the "live_state" field.
func (u *ServiceLinkUpsertOne) ClearLiveState() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.ClearLiveState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceLinkUpsertOne) SetUpdatedAt(v time.Time) *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceLinkUpsertOne) UpdateUpdatedAt() *ServiceLinkUpsertOne {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ServiceLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ServiceLinkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ServiceLinkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ServiceLinkCreateBulk is the builder for creating many ServiceLink entities in bulk.
type ServiceLinkCreateBulk struct {
	config
	err      error
	builders []*ServiceLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the ServiceLink entities in the database.
func (_c *ServiceLinkCreateBulk) Save(ctx context.Context) ([]*ServiceLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServiceLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServiceLinkCreateBulk) SaveX(ctx context.Context) []*ServiceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceLinkUpsert) {
//			SetContainer(v+v).
//		}).
//		Exec(ctx)
func (_c *ServiceLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *ServiceLinkUpsertBulk {
	_c.conflict = opts
	return &ServiceLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ServiceLinkCreateBulk) OnConflictColumns(columns ...string) *ServiceLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ServiceLinkUpsertBulk{
		create: _c,
	}
}

// ServiceLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of ServiceLink nodes.
type ServiceLinkUpsertBulk struct {
	create *ServiceLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ServiceLinkUpsertBulk) UpdateNewValues() *ServiceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ServiceLinkUpsertBulk) Ignore() *ServiceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceLinkUpsertBulk) DoNothing() *ServiceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceLinkCreateBulk.OnConflict
// documentation for more info.
func (u *ServiceLinkUpsertBulk) Update(set func(*ServiceLinkUpsert)) *ServiceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetContainer sets the "container" field.
func (u *ServiceLinkUpsertBulk) SetContainer(v string) *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetContainer(v)
	})
}

// UpdateContainer sets the "container" field to the value that was provided on create.
func (u *ServiceLinkUpsertBulk) UpdateContainer() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateContainer()
	})
}

// SetService sets the "service" field.
func (u *ServiceLinkUpsertBulk) SetService(v servicelink.Service) *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetService(v)
	})
}

// UpdateService sets the "service" field to the value that was provided on create.
func (u *ServiceLinkUpsertBulk) UpdateService() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateService()
	})
}

// SetReference sets the "reference" field.
func (u *ServiceLinkUpsertBulk) SetReference(v string) *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetReference(v)
	})
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *ServiceLinkUpsertBulk) UpdateReference() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateReference()
	})
}

// SetLiveState sets the "live_state" field.
func (u *ServiceLinkUpsertBulk) SetLiveState(v string) *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetLiveState(v)
	})
}

// UpdateLiveState sets the "live_state" field to the value that was provided on create.
func (u *ServiceLinkUpsertBulk) UpdateLiveState() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateLiveState()
	})
}

// ClearLiveState clears the value of the "live_state" field.
func (u *ServiceLinkUpsertBulk) ClearLiveState() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.ClearLiveState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceLinkUpsertBulk) SetUpdatedAt(v time.Time) *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceLinkUpsertBulk) UpdateUpdatedAt() *ServiceLinkUpsertBulk {
	return u.Update(func(s *ServiceLinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ServiceLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ServiceLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
